environment:

  matrix:
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install nose"
  - "%PYTHON%\\python.exe -m pip install wheel"

test_script:
  - "%PYTHON%\\python.exe -m nose"
